### ISSUE TITLE
Función get_item

### ISSUE THREAD

**Issue by webchimp** [biohzrdmx/hummingbird-lite#2]
Mi Rulín, tenemos un problema con la function, tiene lo siguiente:
```php
function get_item($var, $key, $default = '') {
	return is_object($var) ?
		( isset( $object->$key ) ? $object->$key : $default ) :
		( isset( $var[$key] ) ? $var[$key] : $default );
}
```

Pero la variable `object` en el caso de ser un objeto no existe, debe cambiarse por `var`.

- - - - - 
**PS** Quería usar los issues a ver que tal :monkey_face:

**Comment by biohzrdmx** [comment]
Fixed!

**Comment by webchimp** [comment]
Thanks!
